package com.routeapp.routebackend.user.entity.accountlog;

public enum UserAccountLogType {
    REGISTERED,
    LOGGED_IN,
    EMAIL_VERIFIED,
    EMAIL_CHANGE_REQUESTED,
    EMAIL_CHANGED,
    USERNAME_CHANGED,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    ACCOUNT_DEACTIVATED,
    ACCOUNT_REACTIVATED,
    ACCOUNT_DELETION_REQUESTED,
    ACCOUNT_DELETION_CANCELLED
}